# Generated by Django 4.1 on 2022-09-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Primer nombre"),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Apellido")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("0", "Contador"),
                            ("1", "Administrador"),
                            ("2", "Economista"),
                            ("3", "Otro"),
                        ],
                        max_length=1,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
            ],
        ),
    ]
