# Generated by Django 4.1 on 2022-09-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hability", models.CharField(max_length=50, verbose_name="Habilidad")),
            ],
            options={
                "verbose_name": "Hability",
                "verbose_name_plural": "Habilities",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="habilities",
            field=models.ManyToManyField(to="employees.hability"),
        ),
    ]
